.\" Manpage for lz78.
.\" Contact gianni.pollina1@gmail.com to correct errors or typos.
.TH man 1 "02 June 2016" "1.0" "lz78 man page"
.SH NAME
lz78 \- compress a set of file
.SH SYNOPSIS
lz78 [-option] [arguments]
.SH DESCRIPTION
lz78 is a compressor based on a Lempel Ziv 78 algorithm--- lz78.linux(1) instead.
.SH OPTIONS
	-c compress a file

	-o output file

	-d decopress a file

	-l --list info on a .lz78 file--
.LP	//Break line
	For each compressed file, list the following fields:
.RS 3 //indentazione di 3 char
     Algorithm: Type of used algorithm

	Size of dictionary: number of maximun nodes available in dictionary

	Size of each symbol: size of symbols
.LP
	File name: name of the original size
.LP
	Size of the original file: size of uncompressed file
.LP	
	compressed size: size of the compressed file
.LP	
	ratio: compression ratio (0.0% if unknown)
.LP	
	Time of last modified: modification time
.LP	
	SHA-1 checksum: used to guaranteee the integrity of the files

.LP
.RS -3 //indentazione -3 char
	-s set dictionary size
.SH EXAMPLES
	
Command to compress a matlab script:

		lz78 -o compressed.lz78 -c script.m

	 Command to decompress a compressed file .lz78:

		lz78 -d compressed.lz78

.SH SEE ALSO
lz78(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Gianni Pollina (gianni.pollina1@gmail.com)